/* =========================================================
 *  친구모아 아일랜드 고정 주민 30명 (여 15 · 남 15)
 *  성격(4레이어 키) → 외형 컨셉을 맞춰 디자인
 *  게임(새 게임 입주 순서)과 캐릭터 디자인 시트(charsheet.html)가 함께 사용
 * ========================================================= */
(() => {
  'use strict';
  const ISLE = (window.ISLE = window.ISLE || {});
  const SK = { fair: 0xffdcc4, light: 0xffd2b4, warm: 0xf2bc94, tan: 0xe0a478, brown: 0xc4855a, deep: 0x9a6440 };
  const base = { species: 'human', eyes: 'dot', brows: 'thin', mouth: 'smile', blush: 0xff9a88, pattern: 'plain', hat: 'none', glasses: 'none', acc: 'none', height: 1, width: 1, sole: 0xffffff };
  const L = o => Object.assign({}, base, o);
  ISLE.CAST = [
    // ======================= 여자 15 =======================
    { id: 'c01', name: '하나', gender: 'F', age: 21, job: '꽃집 막내', keys: { L1: 'PURE', L2: 'EARLY_BIRD', L3: 'SHY', L4: 'GARDEN' },
      concept: '꽃 화관을 쓴 봄날의 꽃집 소녀', phrase: '저… 오늘 핀 꽃이 제일 예뻐요.', signature: '꽃 화관 · 빨간 퍼프 원피스',
      look: L({ skin: SK.fair, hair: 0xd9a050, hairStyle: 'bobbang', eyeKit: 'lash', eyeColor: 0x2f6fd8, lashes: true, top: 'dress', shirt: 0xd8323c, shirt2: 0xffffff, apron: 0xfff2d6, sleeve: 'short', shoes: 0xd8323c, shoeType: 'mary', socks: 0xfff2d6, hat: 'flowercrown', mouth: 'smile', eyes: 'dot' }) },
    { id: 'c02', name: '유리', gender: 'F', age: 19, job: '편의점 알바 · 인플루언서 지망생', keys: { L1: 'FRESH', L2: 'CURIOUS', L3: 'CUTE', L4: 'GOSSIP' },
      concept: '노란 뿔테에 멜빵 원피스, 폰을 놓지 않는 상큼 막내', phrase: '헐 대박! 이거 찍어서 올려야 돼!', signature: '노란 동그란 안경 · 빨간 멜빵 원피스',
      look: L({ skin: SK.brown, hair: 0x4a2a1c, hairStyle: 'twintail', eyeKit: 'big', eyeColor: 0x3a6a8a, lashes: true, top: 'pinafore', shirt: 0xd8343a, shirt2: 0x6ab8f0, pattern: 'stripe', sleeve: 'short', shoes: 0xffd23a, shoeType: 'sneaker', glasses: 'round', glassesColor: 0xffc81e, hairTie: 0xffd23a, mouth: 'grin', eyes: 'dot', hat: 'bigbow', hatColor: 0xffd23a }) },
    { id: 'c03', name: '세아', gender: 'F', age: 24, job: '타로 리더', keys: { L1: 'MYSTIC', L2: 'NIGHT_OWL', L3: 'DREAMY', L4: 'OCCULT' },
      concept: '파도 같은 파란 머리에 히비스커스, 바다를 닮은 몽환 소녀', phrase: '오늘 밤 별자리가… 너를 부르고 있어.', signature: '히비스커스 · 그라데이션 롱스커트',
      look: L({ skin: SK.warm, hair: 0x2f7ae0, hairStyle: 'longwave', eyeKit: 'dreamy', eyeColor: 0x1fa08a, lashes: true, top: 'tank', shirt: 0xb0287a, shirt2: 0xffffff, bottom: 'longskirt', pants: 0x3a7ad8, pattern: 'stripe2', shoes: 0xb07a4a, shoeType: 'sandal', hat: 'hibiscus', hatColor: 0xff2a4a, acc: 'crossbag', accColor: 0x4a8a5a, mouth: 'open', eyes: 'dot' }) },
    { id: 'c04', name: '지수', gender: 'F', age: 27, job: '찻집 사장', keys: { L1: 'ELEGANT', L2: 'DILIGENT', L3: 'FORMAL', L4: 'FASHION' },
      concept: '쪽머리에 진주, 라벤더 원피스의 우아한 찻집 주인', phrase: '차는 서두르면 맛이 없답니다.', signature: '쪽머리 비녀 · 진주 목걸이',
      look: L({ skin: SK.fair, hair: 0x1f1a1e, hairStyle: 'lowbun', eyeKit: 'calm', eyes: 'dot', eyeColor: 0x4a2a3a, lashes: true, top: 'dress', shirt: 0xc8b4ec, shirt2: 0xf4ecff, sleeve: 'short', shoes: 0x3a2a3a, shoeType: 'loafer', acc: 'necklace', accColor: 0xfff8f0, mole: 'R', mouth: 'smile', pattern: 'flower' }) },
    { id: 'c05', name: '민지', gender: 'F', age: 20, job: '곤충 채집가', keys: { L1: 'TOMBOY', L2: 'WANDERER', L3: 'PRANKSTER', L4: 'FISHING' },
      concept: '보라 야구모자에 핑크 카모 셔츠, 잠자리채 든 골목대장', phrase: '야! 방금 그거 봤어? 장수풍뎅이야!', signature: '보라 캡 · 핑크 카모 셔츠',
      look: L({ skin: SK.tan, hair: 0xd8c070, hairStyle: 'pixie', eyeKit: 'round', eyeColor: 0x3a5a3a, top: 'shirt', shirt: 0xf6a8c8, shirt2: 0xd86a98, pattern: 'leaf', sleeve: 'short', bottom: 'shorts', pants: 0x3a5a8a, shoes: 0xd8b088, shoeType: 'sneaker', socks: 0xffffff, hat: 'cap', hatColor: 0x8a3ae0, mouth: 'grin', eyes: 'dot' }) },
    { id: 'c06', name: '소라', gender: 'F', age: 23, job: '정원사', keys: { L1: 'NATURE', L2: 'DILIGENT', L3: 'WARM', L4: 'GARDEN' },
      concept: '머스타드 비니에 초록 후드 원피스, 물뿌리개 든 눈웃음', phrase: '오늘도 새싹이 하나 더 났어~', signature: '머스타드 비니 · 육각 안경',
      look: L({ skin: SK.fair, hair: 0x9ab0b8, hairStyle: 'lowtwin', eyes: 'dot', eyeKit: 'smile', eyeColor: 0x3a2a20, lashes: true, top: 'hoodie', shirt: 0x2ec27e, shirt2: 0xffffff, sleeve: 'long', bottom: 'skirt', pants: 0x2ec27e, legwear: 0x3a3a44, shoes: 0xd8343a, shoeType: 'sneaker', hat: 'knit', hatColor: 0xe8a81e, glasses: 'square', glassesColor: 0x2b2b30, mouth: 'grin', hairTie: 0xe8a81e }) },
    { id: 'c07', name: '은비', gender: 'F', age: 18, job: '인형 가게 점원', keys: { L1: 'CUTIE', L2: 'HOMEBODY', L3: 'CUTE', L4: 'FASHION' },
      concept: '핑크 뽀글 머리에 프릴 머리띠, 하트 뿅뿅 큐티', phrase: '꺄~ 이거 너무 귀엽잖아! 하트 뿅!', signature: '프릴 머리띠 · 핑크 원피스',
      look: L({ skin: SK.fair, hair: 0xff9ac0, hairStyle: 'curlybob', eyeKit: 'sparkle', eyes: 'dot', eyeColor: 0x2f5fd0, lashes: true, top: 'dress', shirt: 0xffc8dc, shirt2: 0xffffff, pattern: 'heart', sleeve: 'short', shoes: 0xff8fb1, shoeType: 'mary', socks: 0xffffff, hat: 'headband', hatColor: 0xffe0ec, mouth: 'grin' }) },
    { id: 'c08', name: '다은', gender: 'F', age: 22, job: '도서관 사서 보조', keys: { L1: 'SCHOLARLY', L2: 'CURIOUS', L3: 'SHY', L4: 'STUDY' },
      concept: '민트 버킷햇에 양 땋은 머리, 책 냄새 좋아하는 탐구생', phrase: '…저, 이 책 혹시 읽어보셨어요?', signature: '민트 버킷햇 · 양 땋은 머리',
      look: L({ skin: SK.light, hair: 0x7ab0b0, hairStyle: 'braids', eyeKit: 'calm', eyeColor: 0x2f6a8a, lashes: true, top: 'knitvest', shirt: 0xffffff, shirt2: 0xffffff, shoes: 0x8a5a3b, shoeType: 'loafer', socks: 0xffffff, hat: 'bucket', hatColor: 0x6ad0d0, hairTie: 0xffffff, mouth: 'smile', eyes: 'dot', vest: 0xc8a46a, bottomPattern: 'plaid', bottom: 'pleats', pants: 0x3a6a5a, glasses: 'round', glassesColor: 0x8a5a3b }) },
    { id: 'c09', name: '나비', gender: 'F', age: 21, job: '프로게이머 지망생', keys: { L1: 'GAMER', L2: 'NIGHT_OWL', L3: 'CYNICAL', L4: 'MUSIC' },
      concept: '목에 건 헤드폰, 오버핏 보라 후디의 밤샘 게이머', phrase: '…한 판만 더. 진짜 이번이 마지막.', signature: '목 헤드폰 · 오버핏 후디',
      look: L({ skin: SK.fair, hair: 0x2a2030, hairStyle: 'sidepony', eyeKit: 'tired', eyes: 'dot', eyeColor: 0x6a3ab0, lashes: true, top: 'hoodie', shirt: 0x7a5ad8, shirt2: 0xffffff, sleeve: 'long', bottom: 'shorts', pants: 0x2b2b30, legwear: 0x2b2b30, shoes: 0xffffff, shoeType: 'sneaker', acc: 'neckphones', accColor: 0xff4f8a, hairTie: 0xff4f8a, mouth: 'flat' }) },
    { id: 'c10', name: '레아', gender: 'F', age: 25, job: '패션 포토그래퍼', keys: { L1: 'CHIC', L2: 'WANDERER', L3: 'CYNICAL', L4: 'FASHION' },
      concept: '히메컷 흑발에 블랙 재킷, 초커 하나로 끝내는 시크함', phrase: '…괜찮네. 딱 거기까지.', signature: '히메컷 · 블랙 재킷 · 초커',
      look: L({ skin: SK.fair, hair: 0x15121a, hairStyle: 'hime', eyeKit: 'sharp', eyeColor: 0x1e1418, lashes: true, top: 'jacket', shirt: 0x1f1f24, shirt2: 0xf4f4f4, sleeve: 'long', bottom: 'pleats', pants: 0x6a6a72, shoes: 0x1f1f24, shoeType: 'boots', acc: 'choker', accColor: 0x1f1f24, acc2: 'camera', mouth: 'flat', eyes: 'dot' }) },
    { id: 'c11', name: '보미', gender: 'F', age: 26, job: '빵집 사장', keys: { L1: 'LAZY', L2: 'SLOTH', L3: 'DREAMY', L4: 'FOOD' },
      concept: '똥머리에 노란 가디건, 갓 구운 빵 냄새 나는 느긋한 언니', phrase: '음~ 일단 빵부터 먹고 생각하자~', signature: '똥머리 · 버터 가디건 · 에코백',
      look: L({ skin: SK.light, hair: 0x8a5a3b, hairStyle: 'bun', eyeKit: 'droopy', eyeColor: 0xe8b830, lashes: true, top: 'cardigan', shirt: 0xffd86a, shirt2: 0xffffff, bottom: 'longskirt', pants: 0xa8c8a0, shoes: 0xfff4e0, shoeType: 'mary', acc: 'tote', accColor: 0xf3ead8, hairTie: 0xffd86a, freckles: true, mouth: 'open', eyes: 'dot' }) },
    { id: 'c12', name: '아린', gender: 'F', age: 23, job: '거리 싱어송라이터', keys: { L1: 'MUSICIAN', L2: 'NIGHT_OWL', L3: 'PASSIONATE', L4: 'MUSIC' },
      concept: '옆가르마 웨이브에 청재킷, 버스킹 무대의 주인공', phrase: '오늘 밤 공원에서 신곡 불러! 꼭 와!', signature: '청재킷 · 옆가르마 롱',
      look: L({ skin: SK.warm, hair: 0xa8442a, hairStyle: 'sidelong', eyeKit: 'flat', eyeColor: 0x6a3a1a, lashes: true, top: 'jacket', shirt: 0x5a86c8, shirt2: 0x2b2b30, sleeve: 'long', bottom: 'jeans', pants: 0x2a3a5a, shoes: 0xf4f4f4, shoeType: 'sneaker', acc: 'pendant', mouth: 'grin', eyes: 'dot' }) },
    { id: 'c13', name: '수아', gender: 'F', age: 24, job: '섬 자경단장', keys: { L1: 'LEADER', L2: 'EARLY_BIRD', L3: 'PASSIONATE', L4: 'FITNESS' },
      concept: '포니테일에 빨간 제복 코트, 섬을 지키는 열혈 리더', phrase: '다들 모여! 오늘 순찰은 내가 앞장선다!', signature: '빨간 제복 · 흰 벨트 · 블랙 부츠',
      look: L({ skin: SK.light, hair: 0xd8a860, hairStyle: 'pony', eyeKit: 'sharp', eyeColor: 0x3a6a3a, lashes: true, top: 'uniform', shirt: 0xd02a30, shirt2: 0x2b2b30, accColor: 0xffffff, sleeve: 'long', bottom: 'pants', pants: 0xb02028, shoes: 0x1f1f24, shoeType: 'boots', hairTie: 0x1f1f24, brows: 'thick', mouth: 'open', eyes: 'dot' }) },
    { id: 'c14', name: '말순', gender: 'F', age: 71, job: '뜨개 공방 할머니', keys: { L1: 'CLASSIC', L2: 'EARLY_BIRD', L3: 'WARM', L4: 'CLEAN' },
      concept: '뭉게 은발 파마에 니트, 동네 모두의 할머니', phrase: '아이고 우리 강아지, 밥은 먹었니?', signature: '은발 뭉게 파마 · 동그란 안경',
      look: L({ skin: SK.deep, hair: 0x8a8a90, hairStyle: 'cloud', eyeKit: 'smile', eyeColor: 0x6a6a72, top: 'sweater', shirt: 0x3a8a6a, shirt2: 0xffffff, sleeve: 'long', bottom: 'longskirt', pants: 0x6a4a3a, shoes: 0x3a2a24, shoeType: 'loafer', glasses: 'round', glassesColor: 0xb08a4a, acc: 'pendant', mouth: 'open', eyes: 'dot', pattern: 'snow' }) },
    { id: 'c15', name: '루나', gender: 'F', age: 20, job: '연애소설 작가', keys: { L1: 'ROMANTIC', L2: 'HOMEBODY', L3: 'SHY', L4: 'STUDY' },
      concept: '라일락 양쪽 똥머리에 세일러 칼라, 달빛 아래 편지를 쓰는 소녀', phrase: '…오늘 달빛이 예쁜 것 같아. (~랄까나)', signature: '양쪽 똥머리 · 세일러 칼라',
      look: L({ skin: SK.fair, hair: 0xc0a0e8, hairStyle: 'odango', eyeKit: 'lash', eyeColor: 0x7a4ab0, lashes: true, top: 'sailor', shirt: 0xfff8fc, shirt2: 0x4a5aa8, accColor: 0xff5a7a, sleeve: 'short', bottom: 'pleats', pants: 0x4a5aa8, shoes: 0x3a2a3a, shoeType: 'mary', socks: 0xffffff, hairTie: 0xff8fb1, mouth: 'smile', eyes: 'dot', hat: 'hairclip', hatColor: 0xff8fb1 }) },
    // ======================= 남자 15 =======================
    { id: 'c16', name: '준', gender: 'M', age: 20, job: '축구부 에이스', keys: { L1: 'ATHLETIC', L2: 'BUSYBODY', L3: 'PASSIONATE', L4: 'FITNESS' },
      concept: '노란 10번 저지에 빨간 백팩, 달리면서 인사하는 에이스', phrase: '사랑도 운동이야! 직진해라!!!', signature: '노란 10번 저지 · 빨간 백팩',
      look: L({ skin: SK.deep, hair: 0x3a2a24, hairStyle: 'spiky', eyeKit: 'round', eyeColor: 0x4a4a52, top: 'jersey', shirt: 0xffd81e, shirt2: 0x1f8a3a, jerseyNo: 10, jerseyLabel: 'FMIS', bottom: 'shorts', pants: 0x3a5aa8, shoes: 0x2b2b30, shoeType: 'sandal', acc: 'backpack', accColor: 0xd8343a, mouth: 'grin', brows: 'thick', eyes: 'dot' }) },
    { id: 'c17', name: '하루', gender: 'M', age: 25, job: '목수', keys: { L1: 'EXTROVERT', L2: 'EARLY_BIRD', L3: 'WARM', L4: 'FOOD' },
      concept: '빨간 반다나에 숲 티셔츠, 도끼 대신 웃음을 든 목수', phrase: '하하! 오늘도 날씨 최고다! 밥 먹었어?', signature: '페이즐리 반다나 · 초록 장화',
      look: L({ skin: SK.light, hair: 0x3a2a24, hairStyle: 'boyshort', eyes: 'dot', eyeKit: 'smile', eyeColor: 0x3a2a20, top: 'shirt', shirt: 0xf4f4f4, shirt2: 0x2a8a5a, bottom: 'cargo', pants: 0xc8b088, shoes: 0x2a7a3a, shoeType: 'boots', hat: 'bandana', hatColor: 0xd8343a, acc: 'crossbag', accColor: 0x8a6a4a, mouth: 'grin', pattern: 'plaid', sleeve: 'short' }) },
    { id: 'c18', name: '해원', gender: 'M', age: 22, job: '낚시꾼', keys: { L1: 'ADVENTURER', L2: 'WANDERER', L3: 'DREAMY', L4: 'FISHING' },
      concept: '주황 버킷햇에 민트 머리, 반쯤 감은 눈으로 바다만 보는 낚시꾼', phrase: '…물때가 좋네. 오늘은 큰 놈 온다.', signature: '주황 버킷햇 · 낚시 조끼',
      look: L({ skin: SK.fair, hair: 0x3aa08a, hairStyle: 'sideswept', eyeKit: 'sleepy', eyes: 'dot', eyeColor: 0x2a6a5a, top: 'jacket', shirt: 0x5a5f6a, shirt2: 0xf4f4f4, sleeve: 'short', bottom: 'cargo', pants: 0xb8a070, shoes: 0x2a3a6a, shoeType: 'boots', hat: 'bucket', hatColor: 0xe8742a, acc: 'crossbag', accColor: 0x3a7ad8, mouth: 'open' }) },
    { id: 'c19', name: '도윤', gender: 'M', age: 29, job: '스카이라운지 지배인', keys: { L1: 'DANDY', L2: 'DILIGENT', L3: 'FORMAL', L4: 'FASHION' },
      concept: '올백에 네이비 수트, 문을 열어주는 매너남', phrase: '괜찮다면… 오늘 저녁, 시간을 주시겠어요?', signature: '올백 · 네이비 수트 · 와인 넥타이',
      look: L({ skin: SK.light, hair: 0x2b1e18, hairStyle: 'slick', eyeKit: 'calm', eyes: 'dot', eyeColor: 0x3a2a20, top: 'jacket', shirt: 0x24304e, shirt2: 0xffffff, bottom: 'pants', pants: 0x24304e, shoes: 0x3a2018, shoeType: 'loafer', acc: 'tie', accColor: 0x8a1a2a, mouth: 'smile' }) },
    { id: 'c20', name: '시우', gender: 'M', age: 21, job: '헌책방 알바', keys: { L1: 'INTROVERT', L2: 'HOMEBODY', L3: 'SHY', L4: 'STUDY' },
      concept: '5:5 가르마에 베이지 가디건, 동그란 안경 너머 수줍은 책벌레', phrase: '…아, 안녕하세요. 이 책… 재밌어요.', signature: '동그란 안경 · 베이지 가디건',
      look: L({ skin: SK.fair, hair: 0x1f1a1e, hairStyle: 'curtain', eyeKit: 'droopy', eyeColor: 0x3a2a20, top: 'knitvest', shirt: 0xffffff, shirt2: 0xffffff, bottom: 'wide', pants: 0x6a6e78, shoes: 0x3a2a24, shoeType: 'loafer', glasses: 'round', glassesColor: 0x2b2b30, mouth: 'smile', eyes: 'dot', vest: 0xd8c49a }) },
    { id: 'c21', name: '레오', gender: 'M', age: 23, job: '그래피티 아티스트 · DJ', keys: { L1: 'HIP', L2: 'NIGHT_OWL', L3: 'PRANKSTER', L4: 'MUSIC' },
      concept: '빨간 캡에 블랙 가죽 재킷, 금 체인의 힙스터', phrase: '요~ 오늘 클럽에 비밀 셋 있다? 너만 알려줌 ㅋㅋ', signature: '빨간 캡 · 가죽 재킷 · 금 체인',
      look: L({ skin: SK.tan, hair: 0xe8743a, hairStyle: 'wavyshort', eyeKit: 'heavy', eyeColor: 0x2a7a8a, top: 'jacket', shirt: 0x1f1f24, shirt2: 0xd8343a, bottom: 'jeans', pants: 0x2b2b30, shoes: 0xffffff, shoeType: 'sneaker', sole: 0xd8343a, hat: 'cap', hatColor: 0xc02a2a, acc: 'chain', mouth: 'grin', eyes: 'dot' }) },
    { id: 'c22', name: '태오', gender: 'M', age: 22, job: '정원 관리인', keys: { L1: 'CRANKY', L2: 'DILIGENT', L3: 'CYNICAL', L4: 'GARDEN' },
      concept: '덥수룩한 흑발에 빨간 야구점퍼, 툴툴대며 꽃에 물 주는 츤데레', phrase: '내가 물 주고 싶어서 준 거 아니거든?', signature: '덥수룩 흑발 · 빨강/검정 야구점퍼',
      look: L({ skin: SK.fair, hair: 0x15121a, hairStyle: 'messyfringe', eyeKit: 'sanpaku', eyeColor: 0xc04a2a, brows: 'angry', top: 'varsity', shirt: 0xc02a30, shirt2: 0x1f1f24, accColor: 0xffffff, bottom: 'pants', pants: 0xb02028, shoes: 0xc02a30, shoeType: 'boots', mouth: 'pout', eyes: 'dot' }) },
    { id: 'c23', name: '키라', gender: 'M', age: 24, job: '항구 관제사', keys: { L1: 'CHARISMA', L2: 'WANDERER', L3: 'FORMAL', L4: 'STUDY' },
      concept: '갈색 커튼 머리에 하늘색 제복, 조용히 무리를 이끄는 카리스마', phrase: '…괜찮아. 내가 끝까지 지킬게.', signature: '하늘색 제복 · 흰 바지',
      look: L({ skin: SK.fair, hair: 0x6a3a22, hairStyle: 'tiedlong', eyeKit: 'sharp', eyeColor: 0x5a6a8a, top: 'uniform', shirt: 0x8fc0e8, shirt2: 0x24304e, accColor: 0x24304e, bottom: 'pants', pants: 0xf4f4f4, shoes: 0x5a86c8, shoeType: 'sneaker', mouth: 'smile', eyes: 'dot', hairTie: 0x24304e }) },
    { id: 'c24', name: '민호', gender: 'M', age: 22, job: '벽화 화가', keys: { L1: 'ARTISTIC', L2: 'CURIOUS', L3: 'DREAMY', L4: 'STUDY' },
      concept: '바가지 머리에 베레모, 줄무늬 니트의 4차원 화가', phrase: '저 구름… 고래 같지 않아? 그려야겠다.', signature: '베레모 · 줄무늬 니트',
      look: L({ skin: SK.light, hair: 0xe8c070, hairStyle: 'bowl', eyeKit: 'ring', eyeColor: 0x3a2a20, top: 'overalls', shirt: 0xf4f0e6, shirt2: 0x2a4a8a, pattern: 'stripe', bottom: 'pants', pants: 0xb07a4a, shoes: 0x2b2b30, shoeType: 'loafer', hat: 'beret', hatColor: 0xd8343a, acc: 'satchel', accColor: 0x6a4a30, mouth: 'open', eyes: 'dot' }) },
    { id: 'c25', name: '동희', gender: 'M', age: 20, job: '과수원 일꾼', keys: { L1: 'CLUMSY', L2: 'SLOTH', L3: 'CUTE', L4: 'FOOD' },
      concept: '초록 니트캡에 줄무늬 스웨터, 배랑 사과를 양손에 든 허당', phrase: '어? 어어? 사과 굴러간다~!', signature: '초록 니트캡 · 펜던트',
      look: L({ skin: SK.fair, hair: 0x1f1a1e, hairStyle: 'curlyshort', eyeKit: 'bean', eyes: 'dot', eyeColor: 0x3a2a20, top: 'sweater', shirt: 0x2a3a6a, shirt2: 0xf4f4f4, pattern: 'stripe', bottom: 'pants', pants: 0x8a2a2a, shoes: 0xb07a4a, shoeType: 'loafer', hat: 'none', hatColor: 0x2a9a5a, acc: 'pendant', mouth: 'smile' }) },
    { id: 'c26', name: '강선장', gender: 'M', age: 28, job: '페리 선장', keys: { L1: 'SNOB', L2: 'EARLY_BIRD', L3: 'FORMAL', L4: 'FISHING' },
      concept: '닻 마크 선장 모자에 흰 제복, 바다의 신사', phrase: '출항 5분 전입니다. 예의는 바다보다 깊어야지요.', signature: '선장 모자 · 흰 제복 코트',
      look: L({ skin: SK.light, hair: 0x1f1a1e, hairStyle: 'sweptfringe', eyeKit: 'smug', eyeColor: 0x3a3a44, top: 'coat', shirt: 0xf4f4f4, shirt2: 0x2b2b30, sleeve: 'long', bottom: 'pants', pants: 0x2b2b30, shoes: 0x1f1f24, shoeType: 'boots', hat: 'captain', mouth: 'open', eyes: 'dot' }) },
    { id: 'c27', name: '유진', gender: 'M', age: 19, job: '사진관 막내', keys: { L1: 'BEAGLE', L2: 'BUSYBODY', L3: 'PRANKSTER', L4: 'GOSSIP' },
      concept: '금발 웨이브에 왕 동그란 안경, 가만히 못 있는 비글', phrase: '깜짝이야? ㅋㅋㅋ 방금 표정 찍었지롱!', signature: '왕 동그란 안경 · 파란 점퍼',
      look: L({ skin: SK.fair, hair: 0xe8c070, hairStyle: 'fluffy', eyeKit: 'big', eyeColor: 0x5a5a62, top: 'jacket', shirt: 0x8fc0f0, shirt2: 0xffffff, bottom: 'pants', pants: 0xe8e8ec, shoes: 0x3a5a8a, shoeType: 'sneaker', glasses: 'round', glassesColor: 0x1f1f24, acc: 'camera', mouth: 'grin', eyes: 'dot' }) },
    { id: 'c28', name: '진', gender: 'M', age: 21, job: '약국 인턴', keys: { L1: 'ANXIOUS', L2: 'HOMEBODY', L3: 'SHY', L4: 'CLEAN' },
      concept: '네이비 비니에 하늘색 티, 늘 손 소독제를 챙기는 걱정쟁이', phrase: '저기… 감기 기운 있는 거 아니죠? 괜찮아요?', signature: '네이비 비니 · 하늘색 티',
      look: L({ skin: SK.fair, hair: 0x7a9ac8, hairStyle: 'buzz', eyeKit: 'tired', eyeColor: 0x2f5aa8, brows: 'worried', top: 'tee', shirt: 0xbfe0f4, shirt2: 0xffffff, bottom: 'pants', pants: 0xbfe0f4, shoes: 0xf4f4f4, shoeType: 'sneaker', hat: 'knit', hatColor: 0x24304e, mouth: 'flat', eyes: 'dot', pattern: 'star' }) },
    { id: 'c29', name: '이안', gender: 'M', age: 24, job: '숲 해설가 · 정원사', keys: { L1: 'NATURE', L2: 'EARLY_BIRD', L3: 'WARM', L4: 'GARDEN' },
      concept: '보터햇에 체크 셔츠, 초록 멜빵바지의 숲 해설가', phrase: '쉿, 저기 새 소리 들려? 오늘은 동박새야.', signature: '보터햇 · 초록 멜빵바지',
      look: L({ skin: SK.warm, hair: 0x5a3a22, hairStyle: 'sideswept', hairFlip: true, eyeKit: 'smile', eyes: 'dot', eyeColor: 0x4a3020, top: 'overalls', shirt: 0xe8d8b8, shirt2: 0xb8442a, pattern: 'plaid', sleeve: 'short', bottom: 'pants', pants: 0x3a7a4a, shoes: 0x6a4028, shoeType: 'boots', hat: 'boater', hatColor: 0xe8c870, accColor: 0x3a7a4a, mouth: 'smile' }) },
    { id: 'c30', name: '로이', gender: 'M', age: 26, job: '편집숍 사장', keys: { L1: 'FASHIONISTA', L2: 'WANDERER', L3: 'PASSIONATE', L4: 'FASHION' },
      concept: '맨번에 선글라스, 핑크 알로하 셔츠의 패셔니스타', phrase: '오늘 핏 미쳤다! 이 셔츠 어디서 샀냐고? 비밀~', signature: '맨번 · 선글라스 · 알로하 셔츠',
      look: L({ skin: SK.tan, hair: 0x2b1e18, hairStyle: 'manbun', eyeKit: 'round', eyeColor: 0x3a2a20, top: 'aloha', shirt: 0xf6b8d0, shirt2: 0xffffff, pattern: 'flower', sleeve: 'short', bottom: 'pants', pants: 0x1f1f24, shoes: 0xf4f4f4, shoeType: 'sneaker', glasses: 'sun', glassesColor: 0x1f1f24, hat: 'fedora', hatColor: 0xf4f0e6, acc: 'chain', mouth: 'grin', eyes: 'dot' }) },
  ];
})();
